### ISSUE TITLE
edge contrast

### ISSUE THREAD

**Issue by CSV-12** [wilfredwee/photon-australis#57]
Love what you did to Quantum tabs.  
It could be better for multiple tabs, if their outlines were visible while not active.
 
![astralis](https://user-images.githubusercontent.com/29374477/47960794-2b72c900-dfce-11e8-9e2b-5aa118fc234f.png)
Why the hell Mozilla went all fascist on their browser I don't get.

**Comment by CSV-12** [comment]
![astralistabs2](https://user-images.githubusercontent.com/29374477/48303145-a0656780-e4d4-11e8-8e59-e6188a807cb0.png)

**Comment by CSV-12** [comment]
![astralistabs1](https://user-images.githubusercontent.com/29374477/48303153-b541fb00-e4d4-11e8-97c4-db7cc191d87a.png)

Legible tabs

**Comment by wilfredwee** [comment]
Hi there,

Sorry for the very late reply! I appreciate the feedback and examples. However, I left the outlines not visible as a stylistic choice. It should be fairly simple to fork this project and make small modifications to the code in order to achieve the look you desire.

Other people have come up with their own modifications, you may further discuss this in this thread: https://github.com/wilfredwee/photon-australis/issues/22

**Comment by CSV-12** [comment]
My old eyes with progressive lenses like functional more than stylistic.
