### ISSUE TITLE
Tabs are not full height

### ISSUE THREAD

**Issue by ntucker** [wilfredwee/photon-australis#7]
One thing I really liked about Firefox 56's tab design was that the tabs went all the way flush with the top. Currently this theme leaves a few pixels which detracts pretty substantially from it IMO.

Thanks for the work on this though!

**Comment by wilfredwee** [comment]
Thanks for the feedback, the height/margin calculation right now are pretty hacky. I'll see what I can do.

**Comment by Yaron10** [comment]
Hello @wilfredwee,

I've recently upgraded from Firefox 52 to Firefox 64.
You've saved me a lot of work. Thank you. :+1: 

Removing
```
.tab-stack {
  margin-top: 2px !important;
}
```
and adding
```
#nav-bar { margin-top: -2px !important; }
#TabsToolbar[movingtab] + #nav-bar { margin-top: -17px !important; }
```
works for me on Windows 7 Classic Theme.

**Comment by wilfredwee** [comment]
Hi,

Thanks for looking into this! Glad it's working for you. However, I've tried it out on Linux currently and the height calculations are off when hovering inactive tabs and new tab button. Also, height calculations are off when dragging the tabs.

I'm hesitant to fix this issue anytime soon because the current implementation is 'good enough', there is around a 2-3px margin at the top, and moving the cursor all the way to the top of the window and selecting tabs works well.

**Comment by Yaron10** [comment]
Hello,

The current implementation is certainly good as it is. :)
Thanks again.

Best regards.
