### ISSUE TITLE
Design Feedback & Requests

### ISSUE THREAD

**Issue by wozmatic** [wilfredwee/photon-australis#8]
Looks good, see this image for some thoughts on everything

[https://i.imgur.com/sbGpUuW.png](https://i.imgur.com/sbGpUuW.png)

**Comment by wilfredwee** [comment]
Thanks for the feedback! I'll see what I can do. Pull requests always welcomed!

**Comment by Blu3wolf** [comment]
Similar thoughts. In particular I cant see the borders of the other tabs. 

Ive had a quick look to see if I can fix it myself, but Im not sure about the classes here - I can use CSS a little, but I dont know which classes affect which parts of the tabs. Hence my comment rather than a PR.

**Comment by citbr** [comment]
This is just what I was coming in to ask about.  Other than the active tab, and any tabs I hover over, none have a clearly defined outline - they just sort of fade into the theme background, and all you see is the text and favicon.  I'm using a light blue theme, so either a gray line defining the tab edges or a way to specify a specific color and opacity (basically a color tint) for each type of tab would work for me.

**Comment by Blu3wolf** [comment]
I dont even get hover effects, actually!

**Comment by doej1367** [comment]
just wanted to mention this here.
In the old version of Firefox, the other tabs had no outline as well, but there were 
+ vertical lines between those tabs
(i think they realy need outlines. Any outlines. When i first saw it, I thought this would be a bug...)

and you could see the 
+ crosses to close them on every tab 
(which isn't that important because you can middle click to close them as well)

and at last the view more tabs is already correct, if compared to this old version of Firefox.
In my opinion: these
+ don't need to have a curve

'- exept @wozmatic realy badly wants them to ;)
